"https://www.geeksforgeeks.org/problems/largest-sum-subarray-of-size-at-least-k3121/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article",
const binSrch = [
  // "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/",
  // "https://leetcode.com/problems/search-insert-position/description/",
  // "https://leetcode.com/problems/find-first-and-last-position-of-element-in-sorted-array/description/",
  // "https://leetcode.com/problems/search-in-rotated-sorted-array/description/",
  // "https://leetcode.com/problems/search-in-rotated-sorted-array-ii/description/",
  // "https://leetcode.com/problems/find-minimum-in-rotated-sorted-array/description/",
  // "https://leetcode.com/problems/element-appearing-more-than-25-in-sorted-array/description/",
  // "https://leetcode.com/problems/single-element-in-a-sorted-array/description/",
  // "https://leetcode.com/problems/find-peak-element/description/",
  // "https://leetcode.com/problems/sqrtx/description/",
  // "https://leetcode.com/problems/sqrtx/solutions/129247/extension-how-to-find-a-root-of-any-number/",
  "https://www.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1",
  // "https://leetcode.com/problems/koko-eating-bananas/description/",
  "https://leetcode.com/problems/minimum-number-of-days-to-make-m-bouquets/description/",
  // "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/description/",
  // "https://leetcode.com/problems/capacity-to-ship-packages-within-d-days/description/",
  // "https://leetcode.com/problems/kth-missing-positive-number/description/",
  "https://practice.geeksforgeeks.org/problems/aggressive-cows/0",
  "https://leetcode.com/problems/magnetic-force-between-two-balls/description/",
  "https://practice.geeksforgeeks.org/problems/allocate-minimum-number-of-pages0937/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/the-painters-partition-problem1535/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/minimize-max-distance-to-gas-station/1",
  "https://leetcode.com/problems/median-of-two-sorted-arrays/description/",
  "https://practice.geeksforgeeks.org/problems/k-th-element-of-two-sorted-array1317/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  // "https://leetcode.com/problems/row-with-maximum-ones/description/",
  "https://leetcode.com/problems/search-a-2d-matrix/description/",
  "https://leetcode.com/problems/search-a-2d-matrix-ii/description/",
  "https://leetcode.com/problems/find-a-peak-element-ii/description/",
  "https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/find-k-th-smallest-pair-distance/description/", ///////////////////////////////////////////////////
  "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/description/",
  "https://leetcode.com/problems/kth-smallest-element-in-a-sorted-matrix/description/",
  "https://leetcode.com/problems/k-th-smallest-prime-fraction/description/",
  "https://leetcode.com/problems/kth-smallest-number-in-multiplication-table/description/",
  "https://leetcode.com/problems/132-pattern/description/",
  "https://leetcode.com/problems/longest-duplicate-substring/description/",
  "https://leetcode.com/problems/sum-of-mutated-array-closest-to-target/description/",
  "https://leetcode.com/problems/split-array-largest-sum/description/",
  "https://leetcode.com/problems/maximum-average-subarray-ii/description/",
  "https://practice.geeksforgeeks.org/problems/median-in-a-row-wise-sorted-matrix1527/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/number-of-subsequences-that-satisfy-the-given-sum-condition/description/",
  "https://leetcode.com/problems/find-in-mountain-array/description/",
  "https://leetcode.com/problems/max-sum-of-rectangle-no-larger-than-k/description/",
  "https://leetcode.com/problems/heaters/description/",
  "https://leetcode.com/problems/nth-magical-number/description/",
  "https://leetcode.com/problems/time-based-key-value-store/description/",
  "https://leetcode.com/problems/find-the-smallest-divisor-given-a-threshold/description/",
  "https://leetcode.com/problems/count-negative-numbers-in-a-sorted-matrix/description/",
  "https://leetcode.com/problems/minimum-operations-to-reduce-x-to-zero/description/",
  "https://leetcode.com/problems/minimum-limit-of-balls-in-a-bag/description/",
  "https://leetcode.com/problems/minimum-absolute-sum-difference/description/",
  "https://leetcode.com/problems/frequency-of-the-most-frequent-element/description/",
  "https://leetcode.com/problems/most-beautiful-item-for-each-query/description/",
  "https://leetcode.com/problems/minimized-maximum-of-products-distributed-to-any-store/description/",
  "https://leetcode.com/problems/maximum-running-time-of-n-computers/description/",
];
const strings = [
  "https://leetcode.com/problems/largest-odd-number-in-string/description/",
  "https://leetcode.com/problems/isomorphic-strings/description/",
  "https://leetcode.com/problems/maximum-nesting-depth-of-the-parentheses/description/",
  "https://leetcode.com/problems/count-number-of-homogenous-substrings/description/",
  "https://leetcode.com/problems/sum-of-beauty-of-all-substrings/description/",
  "https://leetcode.com/problems/minimum-add-to-make-parentheses-valid/description/",
  "https://leetcode.com/problems/count-and-say/description/",
  "https://leetcode.com/problems/repeated-string-match/description/",
  "https://leetcode.com/problems/find-the-index-of-the-first-occurrence-in-a-string/description/",
  "https://leetcode.com/problems/shortest-palindrome/description/",
  "https://leetcode.com/problems/longest-happy-prefix/description/",
  "https://leetcode.com/problems/count-different-palindromic-subsequences/description/",
  "https://leetcode.com/problems/minimum-moves-to-convert-string/description/",
  "https://practice.geeksforgeeks.org/problems/search-pattern-rabin-karp-algorithm--141631/1",
  "https://practice.geeksforgeeks.org/problems/search-pattern0205/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/search-pattern-z-algorithm--141631/1",
  "https://leetcode.com/problems/number-of-wonderful-substrings/description/",
  "https://leetcode.com/problems/find-the-closest-palindrome/description/",
  "https://leetcode.com/problems/valid-palindrome-ii/description/",
  "https://leetcode.com/problems/custom-sort-string/description/",
  "https://leetcode.com/problems/score-of-parentheses/description/",
  "https://leetcode.com/problems/compare-version-numbers/description/",
  "https://leetcode.com/problems/longest-chunked-palindrome-decomposition/description/",
  "https://leetcode.com/problems/break-a-palindrome/description/",
  "https://leetcode.com/problems/can-make-palindrome-from-substring/description/",
  "https://leetcode.com/problems/longest-happy-string/description/",
  "https://leetcode.com/problems/minimum-remove-to-make-valid-parentheses/description/",
  "https://leetcode.com/problems/maximum-number-of-occurrences-of-a-substring/description/",
  "https://leetcode.com/problems/construct-k-palindrome-strings/description/",
  "https://leetcode.com/problems/longest-happy-prefix/description/",
  "https://leetcode.com/problems/check-if-a-string-can-break-another-string/description/",
  "https://leetcode.com/problems/find-longest-awesome-substring/description/",
  "https://leetcode.com/problems/split-two-strings-to-make-palindrome/description/",
  "https://leetcode.com/problems/determine-if-two-strings-are-close/description/",
  // "https://leetcode.com/problems/additive-number/description/",
  "https://leetcode.com/problems/maximum-product-of-word-lengths/description/",
];
const twoPtr$slidingWindow = [
  "https://leetcode.com/problems/longest-substring-without-repeating-characters/description/",
  "https://leetcode.com/problems/max-consecutive-ones-iii/description/",
  "https://leetcode.com/problems/fruit-into-baskets/description/",
  "https://www.geeksforgeeks.org/problems/longest-k-unique-characters-substring0853/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article",
  "https://leetcode.com/problems/number-of-substrings-containing-all-three-characters/description/",
  "https://leetcode.com/problems/longest-repeating-character-replacement/description/",
  "https://leetcode.com/problems/length-of-longest-subarray-with-at-most-k-frequency/description/",
  "https://leetcode.com/problems/count-subarrays-where-max-element-appears-at-least-k-times/description/",
  "https://leetcode.com/problems/binary-subarrays-with-sum/description/",
  "https://leetcode.com/problems/subarrays-with-k-different-integers/description/",
  "https://leetcode.com/problems/count-number-of-nice-subarrays/description/",
  "https://leetcode.com/problems/maximum-points-you-can-obtain-from-cards/description/",
  "https://www.naukri.com/code360/problems/longest-substring-with-at-most-k-distinct-characters_2221410",
  "https://leetcode.com/problems/minimum-window-substring/description/",
  "https://www.geeksforgeeks.org/problems/minimum-window-subsequence/1",
  "https://practice.geeksforgeeks.org/problems/longest-k-unique-characters-substring0853/1",
  "https://practice.geeksforgeeks.org/problems/minimum-window-subsequence/1",
  //
  "https://leetcode.com/discuss/interview-question/917409/google-phone-longest-subarray-sum-at-most-k",
  "https://leetcode.com/problems/pancake-sorting/description/",
  "https://leetcode.com/problems/minimum-length-of-string-after-deleting-similar-ends/description/",
  "https://leetcode.com/problems/sentence-similarity-iii/description/",
  "https://leetcode.com/problems/minimum-adjacent-swaps-to-reach-the-kth-smallest-number/description/",
  "https://leetcode.com/problems/two-sum-ii-input-array-is-sorted/description/",
  "https://leetcode.com/problems/find-the-duplicate-number/description/",
  "https://leetcode.com/problems/circular-array-loop/description/",
  // "https://leetcode.com/problems/minimum-size-subarray-sum/description/",
  "https://leetcode.com/problems/subarray-product-less-than-k/description/",
  "https://leetcode.com/problems/count-subarrays-with-score-less-than-k/description/",
  "https://leetcode.com/problems/get-equal-substrings-within-budget/description/",
  "https://leetcode.com/problems/replace-the-substring-for-balanced-string/description/",
  "https://leetcode.com/problems/longest-nice-subarray/description/",
  "https://leetcode.com/problems/count-the-number-of-good-subarrays/description/",
  "https://leetcode.com/problems/longest-continuous-subarray-with-absolute-diff-less-than-or-equal-to-limit/description/",
  "https://leetcode.com/problems/count-complete-subarrays-in-an-array/description/",
  "https://leetcode.com/problems/find-the-longest-equal-subarray/description/",
  "https://leetcode.com/problems/minimum-size-subarray-in-infinite-array/description/",
  "https://leetcode.com/problems/length-of-longest-subarray-with-at-most-k-frequency/description/",
  "https://leetcode.com/problems/longest-subarray-of-1s-after-deleting-one-element/description/",
  "https://leetcode.com/problems/shortest-subarray-with-sum-at-least-k/description/",
  "https://leetcode.com/problems/maximize-win-from-two-segments/description/",
  "https://leetcode.com/problems/frequency-of-the-most-frequent-element/description/",
  "https://leetcode.com/problems/find-the-longest-semi-repetitive-substring/description/",
  "https://leetcode.com/problems/maximize-the-confusion-of-an-exam/description/",
  "https://leetcode.com/problems/maximum-beauty-of-an-array-after-applying-operation/description/",
  "https://leetcode.com/problems/maximum-number-of-robots-within-budget/description/",
];
const rec$bt = [
  "https://leetcode.com/problems/basic-calculator/description/",
  "https://leetcode.com/problems/string-to-integer-atoi/description/",
  "https://leetcode.com/problems/n-queens/description/",
  "https://leetcode.com/problems/n-queens-ii/description/|",
  "https://www.geeksforgeeks.org/sort-a-stack-using-recursion/",
  "https://leetcode.com/problems/restore-ip-addresses/description/",
  "https://www.geeksforgeeks.org/reverse-a-stack-using-recursion/",
  "https://practice.geeksforgeeks.org/problems/consecutive-1s-not-allowed1912/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/construct-the-lexicographically-largest-valid-sequence/description/",
  "https://practice.geeksforgeeks.org/problems/longest-possible-route-in-a-matrix-with-hurdles/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/sudoku-solver/description/",
  "https://leetcode.com/problems/combination-sum/description/",
  "https://leetcode.com/problems/subsets/description/",
  "https://leetcode.com/problems/remove-invalid-parentheses/description/",
  "https://leetcode.com/problems/cracking-the-safe/description/",
  "https://leetcode.com/problems/combinations/description/",
  "https://leetcode.com/problems/combination-sum/description/",
  "https://leetcode.com/problems/combination-sum-ii/description/",
  "https://leetcode.com/problems/subsets-ii/description/",
  "https://leetcode.com/problems/combination-sum-iii/description/",
  "https://leetcode.com/problems/word-search/description/",
  "https://leetcode.com/problems/word-search-ii/description/",
  "https://leetcode.com/problems/minimum-possible-integer-after-at-most-k-adjacent-swaps-on-digits/description/",
  "https://leetcode.com/problems/flower-planting-with-no-adjacent/description/",
  "https://leetcode.com/problems/verbal-arithmetic-puzzle/description/",
  "https://leetcode.com/problems/expression-add-operators/description/",
  "https://practice.geeksforgeeks.org/problems/tower-of-hanoi-1587115621/1",
  "https://leetcode.com/problems/find-the-winner-of-the-circular-game/description/",
];
const s$q = [
  "conversions pre in post fix:",
  "https://practice.geeksforgeeks.org/problems/prefix-to-infix-conversion/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/prefix-to-postfix-conversion/1",
  "https://practice.geeksforgeeks.org/problems/postfix-to-prefix-conversion/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/postfix-to-infix-conversion/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/infix-to-postfix-1587115620/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://www.geeksforgeeks.org/problems/number-of-nges-to-the-right/1?utm_source=youtube&utm_medium=collab_striver_ytdescription&utm_campaign=number-of-nges-to-the-right",
  "https://practice.geeksforgeeks.org/problems/the-celebrity-problem/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/first-non-repeating-character-in-a-stream1216/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/expression-contains-redundant-bracket-or-not/1",
];
const ll = [
  // "https://leetcode.com/problems/design-linked-list/description/",
  // "https://www.geeksforgeeks.org/problems/arrange-consonants-and-vowels/1",
  // "https://leetcode.com/problems/merge-in-between-linked-lists/description/",
  // "https://leetcode.com/problems/reverse-linked-list/description/",
  // "https://leetcode.com/problems/reverse-linked-list-ii/description/",
  // "https://www.geeksforgeeks.org/problems/reverse-a-doubly-linked-list/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  // "https://leetcode.com/problems/add-two-numbers/description/",
  // "https://leetcode.com/problems/odd-even-linked-list/description/",
  // "https://www.geeksforgeeks.org/problems/given-a-linked-list-of-0s-1s-and-2s-sort-it/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  // "https://leetcode.com/problems/remove-nth-node-from-end-of-list/description/",
  // "https://leetcode.com/problems/palindrome-linked-list/description/",
  // "https://www.geeksforgeeks.org/problems/add-1-to-a-number-represented-as-linked-list/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  // "https://leetcode.com/problems/double-a-number-represented-as-a-linked-list/description/",
  // "https://leetcode.com/problems/intersection-of-two-linked-lists/description/",
  // "https://leetcode.com/problems/middle-of-the-linked-list/description/",
  // "https://leetcode.com/problems/delete-the-middle-node-of-a-linked-list/description/",
  // "https://leetcode.com/problems/linked-list-cycle/description/",
  // "https://leetcode.com/problems/linked-list-cycle-ii/description/",
  // "https://www.geeksforgeeks.org/problems/find-length-of-loop/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  // "https://practice.geeksforgeeks.org/problems/remove-loop-in-linked-list/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  // "https://www.geeksforgeeks.org/problems/delete-all-occurrences-of-a-given-key-in-a-doubly-linked-list/1",
  // "https://www.geeksforgeeks.org/problems/find-pairs-with-given-sum-in-doubly-linked-list/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  // "https://www.geeksforgeeks.org/problems/remove-duplicates-from-a-sorted-doubly-linked-list/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  // "https://www.geeksforgeeks.org/problems/remove-duplicates-from-an-unsorted-linked-list/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  // "https://practice.geeksforgeeks.org/problems/remove-all-occurences-of-duplicates-in-a-linked-list/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  // "https://leetcode.com/problems/remove-duplicates-from-sorted-list/description/",
  "https://leetcode.com/problems/remove-duplicates-from-sorted-list-ii/description/",
  "https://leetcode.com/problems/remove-zero-sum-consecutive-nodes-from-linked-list/description/",
  // "https://leetcode.com/problems/reverse-nodes-in-k-group/description/",
  // "https://leetcode.com/problems/rotate-list/description/",
  // "https://leetcode.com/problems/merge-two-sorted-lists/description/",
  // "https://www.geeksforgeeks.org/problems/linked-list-that-is-sorted-alternatingly/1",
  // "https://www.geeksforgeeks.org/problems/flattening-a-linked-list/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  // "https://leetcode.com/problems/flatten-a-multilevel-doubly-linked-list/",
  // "https://leetcode.com/problems/merge-k-sorted-lists/description/",
  // "https://leetcode.com/problems/sort-list/description/",
  // "https://practice.geeksforgeeks.org/problems/sort-a-linked-list/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/quick-sort-on-linked-list/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  // "https://practice.geeksforgeeks.org/problems/merge-sort-on-doubly-linked-list/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  // "https://leetcode.com/problems/copy-list-with-random-pointer/description/",
  // "https://leetcode.com/problems/design-browser-history",
  // "https://leetcode.com/problems/reorder-list/description/",
  // "https://leetcode.com/problems/next-greater-node-in-linked-list/description/",
  "https://practice.geeksforgeeks.org/problems/delete-nodes-having-greater-value-on-right/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/all-oone-data-structure",
  "https://leetcode.com/problems/design-a-text-editor",
  // "https://practice.geeksforgeeks.org/problems/subtraction-in-linked-list/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
];
const greedy = [
  "https://leetcode.com/problems/valid-parenthesis-string/description/",
  "https://leetcode.com/problems/reveal-cards-in-increasing-order/description/",
  "https://practice.geeksforgeeks.org/problems/n-meetings-in-one-room-1587115620/1",
  "https://leetcode.com/problems/minimum-deletions-to-make-string-k-special/description/",
  // "https://leetcode.com/problems/jump-game-ii/description/",
  // "https://leetcode.com/problems/minimum-number-of-frogs-croaking/description/",
  "https://practice.geeksforgeeks.org/problems/job-sequencing-problem-1587115620/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/candy/description/",
  "https://practice.geeksforgeeks.org/problems/page-faults-in-lru5603/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/insert-interval/description/",
  "https://leetcode.com/problems/merge-intervals/description/",
  "https://leetcode.com/problems/non-overlapping-intervals/description/",
  "https://leetcode.com/problems/minimum-number-of-arrows-to-burst-balloons/description/ intervals",
  "https://leetcode.com/problems/bag-of-tokens/description/",
  "https://leetcode.com/problems/maximum-xor-product/description/",
  "https://leetcode.com/problems/minimum-elements-to-add-to-form-a-given-sum/description/",
  "https://practice.geeksforgeeks.org/problems/minimum-sum-of-absolute-differences-of-pairs/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/pyramid-form3044/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/find-maximum-equal-sum-of-three-stacks/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/smallest-number5829/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/swap-and-maximize5859/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/min-cut-square3303/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/minimum-cost-to-cut-a-board-into-squares/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/overlapping-intervals--170633/1",
  "https://leetcode.com/problems/furthest-building-you-can-reach/description",
  "https://leetcode.com/problems/find-the-maximum-sum-of-node-values/description/",
];
const tree$bst = [
  // "https://leetcode.com/problems/binary-tree-preorder-traversal/description/",
  // "https://leetcode.com/problems/binary-tree-inorder-traversal/description/",
  // "https://leetcode.com/problems/binary-tree-postorder-traversal/description/",
  // ITERATIVE TRAVERSALS
  "https://practice.geeksforgeeks.org/problems/preorder-traversal-iterative/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/inorder-traversal-iterative/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/postorder-traversal-iterative/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab", //post order iterative with - 1, 2 stack
  //all traversal in one traversal
  // "https://leetcode.com/problems/binary-tree-level-order-traversal/description/",
  "https://leetcode.com/problems/maximum-depth-of-binary-tree/description/",
  "https://leetcode.com/problems/balanced-binary-tree/description/",
  "https://leetcode.com/problems/diameter-of-binary-tree/description/",
  "https://leetcode.com/problems/binary-tree-maximum-path-sum/description/",
  "https://leetcode.com/problems/same-tree/description/",
  "https://leetcode.com/problems/binary-tree-zigzag-level-order-traversal/description/",
  "https://practice.geeksforgeeks.org/problems/boundary-traversal-of-binary-tree/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/vertical-order-traversal-of-a-binary-tree/description/",
  "https://www.geeksforgeeks.org/problems/top-view-of-binary-tree/1",
  "https://www.geeksforgeeks.org/problems/bottom-view-of-binary-tree/1",
  "https://leetcode.com/problems/binary-tree-right-side-view/description/",
  "https://www.geeksforgeeks.org/problems/left-view-of-binary-tree/1",
  "https://leetcode.com/problems/symmetric-tree/description/",
  "https://leetcode.com/problems/binary-tree-paths/description/",
  "https://www.geeksforgeeks.org/print-path-root-given-node-binary-tree/",
  "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-tree/description/",
  "https://leetcode.com/problems/maximum-width-of-binary-tree/description/",
  "https://www.geeksforgeeks.org/problems/children-sum-parent/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article",
  "https://leetcode.com/problems/all-nodes-distance-k-in-binary-tree/description/",
  "https://www.geeksforgeeks.org/problems/burning-tree/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article",
  "https://leetcode.com/problems/count-complete-tree-nodes/description/", //theory
  "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-inorder-traversal/description/",
  "https://leetcode.com/problems/construct-binary-tree-from-inorder-and-postorder-traversal/description/",
  "https://leetcode.com/problems/construct-binary-tree-from-preorder-and-postorder-traversal/description/",
  "https://leetcode.com/problems/serialize-and-deserialize-binary-tree/description/",
  //morris traversal all 3
  "https://leetcode.com/problems/flatten-binary-tree-to-linked-list/description/",
  "https://www.geeksforgeeks.org/problems/implementing-ceil-in-bst/1",
  "https://www.geeksforgeeks.org/problems/floor-in-bst/1",
  "https://leetcode.com/problems/insert-into-a-binary-search-tree/description/",
  "https://leetcode.com/problems/delete-node-in-a-bst/description/",
  "https://leetcode.com/problems/kth-smallest-element-in-a-bst/description/",
  "https://leetcode.com/problems/validate-binary-search-tree/description/",
  "https://leetcode.com/problems/lowest-common-ancestor-of-a-binary-search-tree/description/",
  "https://leetcode.com/problems/construct-binary-search-tree-f rom-preorder-traversal/description/",
  "https://www.geeksforgeeks.org/problems/predecessor-and-successor/1",
  "https://leetcode.com/problems/merge-bsts-to-create-single-bst/description/",
  "https://leetcode.com/problems/binary-search-tree-iterator/description/",
  "https://leetcode.com/problems/two-sum-iv-input-is-a-bst/description/",
  "https://leetcode.com/problems/recover-binary-search-tree/description/",
  "https://leetcode.com/problems/maximum-sum-bst-in-binary-tree/description/",
  "https://practice.geeksforgeeks.org/problems/largest-bst/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/construct-a-full-binary-tree/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/check-if-tree-is-isomorphic/1",
  "https://leetcode.com/problems/amount-of-time-for-binary-tree-to-be-infected/description/",
  "https://practice.geeksforgeeks.org/problems/diagonal-traversal-of-binary-tree/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/root-to-leaf-paths/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/distribute-coins-in-binary-tree/description/",
  "https://leetcode.com/tag/tree/",
  "https://leetcode.com/tag/binary-tree/",
  "https://leetcode.com/tag/binary-search-tree/",
];
const heap$hash = [
  "https://leetcode.com/problems/least-number-of-unique-integers-after-k-removals/description/",
  "https://leetcode.com/problems/maximum-subsequence-score/description/",
  "https://practice.geeksforgeeks.org/problems/implementation-of-priority-queue-using-binary-heap/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/count-of-smaller-numbers-after-self/description/",
  "https://practice.geeksforgeeks.org/problems/operations-on-binary-min-heap/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/does-array-represent-heap4345/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/convert-min-heap-to-max-heap-1666385109/1",
  "https://practice.geeksforgeeks.org/problems/rearrange-characters4649/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/rank-transform-of-an-array/description/",
  "https://leetcode.com/problems/task-scheduler/description/",
  "https://practice.geeksforgeeks.org/problems/distinct-palindromic-substrings5141/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/hand-of-straights/description/",
  "https://leetcode.com/problems/design-twitter/description/",
  "https://leetcode.com/problems/subarray-sums-divisible-by-k/description/",
  "https://practice.geeksforgeeks.org/problems/maximum-sum-combination/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/find-median-from-data-stream/description/",
  "https://www.geeksforgeeks.org/online-algorithm-for-checking-palindrome-in-a-stream/",
  "https://leetcode.com/problems/top-k-frequent-elements/description/",
  "https://leetcode.com/problems/top-k-frequent-words/description/",
  "https://leetcode.com/problems/minimum-difference-between-highest-and-lowest-of-k-scores/description/",
  "https://www.geeksforgeeks.org/find-recurring-sequence-fraction/",
  "https://leetcode.com/problems/sort-an-array/description/",
  "https://practice.geeksforgeeks.org/problems/k-largest-elements4206/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://practice.geeksforgeeks.org/problems/next-larger-element-1587115620/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/find-k-closest-elements/description/",
  "https://www.geeksforgeeks.org/tournament-tree-and-binary-heap/",
  "https://leetcode.com/problems/finding-pairs-with-a-certain-sum/description/",
  "https://leetcode.com/problems/single-threaded-cpu/description/",
  "https://practice.geeksforgeeks.org/problems/page-faults-in-lru5603/1?utm_source=geeksforgeeks&utm_medium=ml_article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/lru-cache/description/",
  "https://leetcode.com/problems/lfu-cache/description/",
  "https://leetcode.com/problems/reorganize-string/description/",
  "https://leetcode.com/problems/find-the-kth-smallest-sum-of-a-matrix-with-sorted-rows/description/",
  "https://leetcode.com/problems/merge-k-sorted-lists/description/",
  "https://leetcode.com/problems/find-k-pairs-with-smallest-sums/description/",
  "https://leetcode.com/problems/find-median-from-data-stream/description/",
  "https://leetcode.com/problems/sliding-window-median/description/",
  "https://leetcode.com/problems/ipo/description/",
  "https://leetcode.com/problems/minimum-cost-to-hire-k-workers/description/",
  "https://leetcode.com/problems/number-of-submatrices-that-sum-to-target/description/",
];
const graphs = [
  // "https://leetcode.com/problems/rotting-oranges/",
  // "https://leetcode.com/problems/flood-fill/",
  "https://leetcode.com/problems/01-matrix/description/",
  "https://leetcode.com/problems/surrounded-regions/description/",
  // "https://leetcode.com/problems/number-of-enclaves/description/",
  "https://www.codingninjas.com/studio/problems/distinct-islands_630460?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
  "https://leetcode.com/problems/is-graph-bipartite/description/",
  "https://leetcode.com/problems/course-schedule-i/description/",
  "https://leetcode.com/problems/course-schedule-ii/description/",
  "https://leetcode.com/problems/find-eventual-safe-states/description/",
  "https://leetcode.com/problems/word-ladder/description/",
  "https://leetcode.com/problems/word-ladder-ii/description/",
  // "https://leetcode.com/problems/shortest-path-in-binary-matrix/description/",
  "https://leetcode.com/problems/path-with-minimum-effort/description/",
  "https://leetcode.com/problems/cheapest-flights-within-k-stops/description/",
  "https://www.geeksforgeeks.org/problems/minimum-multiplications-to-reach-end/1",
  "https://leetcode.com/problems/find-all-people-with-secret/description/",
  "https://leetcode.com/problems/number-of-ways-to-arrive-at-destination/description/",
  "https://leetcode.com/problems/find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance/description/",
  // "https://leetcode.com/problems/number-of-provinces/description/",
  "https://leetcode.com/problems/number-of-operations-to-make-network-connected/description/",
  "https://leetcode.com/problems/accounts-merge/description/",
  "https://leetcode.com/problems/making-a-large-island/description/",
  "https://leetcode.com/problems/most-stones-removed-with-same-row-or-column/description/",
  "https://leetcode.com/problems/critical-connections-in-a-network/description/",
  "https://practice.geeksforgeeks.org/problems/alien-dictionary/1",
  "https://leetcode.com/tag/graph/",
  "https://leetcode.com/problems/evaluate-division/description/",
  "https://leetcode.com/problems/reorder-routes-to-make-all-paths-lead-to-the-city-zero/description/",
  "https://leetcode.com/problems/greatest-common-divisor-traversal/description/ DSU",
];
const dp = [
  "https://leetcode.com/problems/frog-jump/description/",
  "https://leetcode.com/problems/frog-jump-ii/description/",
  "https://leetcode.com/problems/house-robber/description/",
  "https://leetcode.com/problems/house-robber-ii/description/",
  "https://www.codingninjas.com/studio/problems/ninja-s-training_3621003",
  "https://leetcode.com/problems/minimum-path-sum/description/",
  "https://leetcode.com/problems/triangle/description/",
  "https://leetcode.com/problems/minimum-falling-path-sum/description/",
  "https://leetcode.com/problems/cherry-pickup/description/",
  "https://leetcode.com/problems/cherry-pickup-ii/description/ 3d",
  "https://www.geeksforgeeks.org/problems/subset-sum-problem-1611555638/1",
  // "https://leetcode.com/problems/partition-equal-subset-sum/description/",
  "https://leetcode.com/problems/partition-array-into-two-arrays-to-minimize-sum-difference/description/",
  "https://www.geeksforgeeks.org/problems/perfect-sum-problem5633/1",
  "https://www.geeksforgeeks.org/problems/partitions-with-given-difference/1",
  "https://leetcode.com/problems/coin-change/description/",
  "https://leetcode.com/problems/target-sum/description/",
  "https://leetcode.com/problems/coin-change-ii/description/",
  "https://practice.geeksforgeeks.org/problems/rod-cutting0840/1?utm_source=geeksforgeeks&utm_medium=article_practice_tab&utm_campaign=article_practice_tab",
  "https://leetcode.com/problems/longest-common-subsequence/description/ strings",
  "https://leetcode.com/problems/maximum-length-of-repeated-subarray/description/",
  "https://leetcode.com/problems/longest-palindromic-subsequence/description/",
  "https://leetcode.com/problems/minimum-insertion-steps-to-make-a-string-palindrome/description/",
  "https://leetcode.com/problems/longest-palindromic-substring/description/",
  "https://leetcode.com/problems/delete-operation-for-two-strings/description/",
  "https://www.geeksforgeeks.org/problems/minimum-number-of-deletions-and-insertions0209/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article",
  "https://leetcode.com/problems/shortest-common-supersequence/description/",
  "https://leetcode.com/problems/distinct-subsequences/description/",
  "https://leetcode.com/problems/edit-distance/description/ 2d strings",
  "https://leetcode.com/problems/wildcard-matching/description/",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-ii/description/",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iii/description/",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-iv/description/",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-cooldown/description/",
  "https://leetcode.com/problems/best-time-to-buy-and-sell-stock-with-transaction-fee/description/ 2d",
  "https://leetcode.com/problems/k-inverse-pairs-array/description/ 2d",
  "https://leetcode.com/problems/longest-increasing-subsequence/description/",
  "https://leetcode.com/problems/longest-increasing-subsequence-ii/description/",
  "https://leetcode.com/problems/largest-divisible-subset/description/ 1d",
  "https://leetcode.com/problems/longest-string-chain/description/",
  "https://leetcode.com/problems/minimum-number-of-removals-to-make-mountain-array/description/",
  "https://leetcode.com/problems/number-of-longest-increasing-subsequence/description/",
  "https://leetcode.com/problems/minimum-cost-to-cut-a-stick/description/",
  "https://leetcode.com/problems/burst-balloons/description/",
  "https://www.geeksforgeeks.org/problems/boolean-parenthesization5610/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article",
  "https://leetcode.com/problems/palindrome-partitioning/description/",
  "https://leetcode.com/problems/palindrome-partitioning-ii/description/",
  "https://leetcode.com/problems/partition-array-for-maximum-sum/description/",
  "https://leetcode.com/problems/count-square-submatrices-with-all-ones/description/",
  //classic
  "https://leetcode.com/problems/regular-expression-matching/description/",
  "https://leetcode.com/problems/maximum-subarray/?envType=list&envId=50wroh7h",
  "https://leetcode.com/problems/interleaving-string/description/",
  "https://leetcode.com/problems/maximum-product-subarray/description/",
  "https://leetcode.com/problems/russian-doll-envelopes/description/",
  "https://leetcode.com/problems/largest-plus-sign/description/",
  "https://leetcode.com/problems/length-of-longest-fibonacci-subsequence/description/",
  "https://leetcode.com/problems/bitwise-ors-of-subarrays/description/",
  "https://leetcode.com/problems/delete-columns-to-make-sorted-iii/description/",
  "https://leetcode.com/problems/longest-turbulent-subarray/description/",
  "https://leetcode.com/problems/maximum-subarray-sum-with-one-deletion/description/",
  "https://leetcode.com/problems/make-array-strictly-increasing/description/",
  "https://leetcode.com/problems/k-concatenation-maximum-sum/?envType=list&envId=50wroh7h",
  "https://leetcode.com/problems/maximum-height-by-stacking-cuboids/description/",
  "https://leetcode.com/problems/max-dot-product-of-two-subsequences/description/",
  //1d
  "https://leetcode.com/problems/unique-binary-search-trees/description/",
  "https://leetcode.com/problems/perfect-squares/description/",
  "https://leetcode.com/problems/counting-bits/description/",
  "https://leetcode.com/problems/integer-break/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/count-numbers-with-unique-digits/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/wiggle-subsequence/description/",
  "https://leetcode.com/problems/student-attendance-record-ii/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/decode-ways-ii/description/",
  "https://leetcode.com/problems/maximum-length-of-pair-chain/description/",
  "https://leetcode.com/problems/delete-and-earn/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/domino-and-tromino-tiling/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/knight-dialer/description/",
  "https://leetcode.com/problems/triples-with-bitwise-and-equal-to-zero/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/minimum-cost-for-tickets/description/",
  "https://leetcode.com/problems/divisor-game/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/filling-bookcase-shelves/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/longest-arithmetic-subsequence-of-given-difference/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/maximum-profit-in-job-scheduling/description/",
  "https://leetcode.com/problems/greatest-sum-divisible-by-three/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/minimum-number-of-taps-to-open-to-water-a-garden/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/count-all-valid-pickup-and-delivery-options/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/restore-the-array/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/stone-game-iii/description/",
  "https://leetcode.com/problems/form-largest-integer-with-digits-that-add-up-to-target/?envType=list&envId=50vlu3z5",
  "https://leetcode.com/problems/stone-game-iv/description/",
  //string
  // "https://leetcode.com/problems/longest-ideal-subsequence/description/",
  "https://leetcode.com/problems/palindromic-substrings/description/",
  "https://leetcode.com/problems/maximum-length-of-a-concatenated-string-with-unique-characters/description/",
  "https://leetcode.com/problems/longest-valid-parentheses/description/",
  "https://leetcode.com/problems/word-break/description/",
  "https://leetcode.com/problems/word-break-ii/description/",
  "https://leetcode.com/problems/is-subsequence/description/",
  "https://www.geeksforgeeks.org/problems/longest-repeating-and-non-overlapping-substring3421/1",
  "https://leetcode.com/problems/count-the-repetitions/?envType=list&envId=50v8wybv",
  "https://leetcode.com/problems/unique-substrings-in-wraparound-string/?envType=list&envId=50v8wybv",
  "https://leetcode.com/problems/wildcard-matching/description/",
  //knapsack
  "https://leetcode.com/problems/ones-and-zeroes/description/",
  "https://leetcode.com/problems/shopping-offers/description/",
  "https://leetcode.com/problems/2-keys-keyboard/description/",
  "https://leetcode.com/problems/minimum-swaps-to-make-sequences-increasing/description/",
  "https://leetcode.com/problems/profitable-schemes/description/",
  "https://leetcode.com/problems/tallest-billboard/description/",
  "https://leetcode.com/problems/pizza-with-3n-slices/description/",
  "https://leetcode.com/problems/reducing-dishes/description/",
  "https://leetcode.com/problems/best-team-with-no-conflicts/description/",
  //decision
  "https://www.geeksforgeeks.org/problems/convert-to-strictly-increasing-array3351/1",
  "https://leetcode.com/problems/soup-servings/description/",
  "https://leetcode.com/problems/number-of-ways-to-stay-in-the-same-place-after-some-steps/description/",
  "https://practice.geeksforgeeks.org/problems/mobile-numeric-keypad5456/1",
  "https://leetcode.com/problems/maximum-strictly-increasing-cells-in-a-matrix/description/",
  //max-min
  "https://leetcode.com/problems/dungeon-game/description/",
  "https://leetcode.com/problems/maximal-square/description/",
  "https://leetcode.com/problems/tiling-a-rectangle-with-the-fewest-squares/description/",
  //grid, multidimensional dp
  "https://leetcode.com/problems/unique-paths/description/",
  "https://leetcode.com/problems/unique-paths-ii/description/",
  "https://leetcode.com/problems/minimum-path-sum/description/",
  "https://www.codingninjas.com/studio/problems/chocolate-pickup_3125885?utm_source=striver&utm_medium=website&utm_campaign=a_zcoursetuf",
  "https://leetcode.com/problems/kth-smallest-instructions/description/",
  "https://leetcode.com/problems/number-of-paths-with-max-score/description/,",
  "https://leetcode.com/problems/where-will-the-ball-fall/description/",
  "https://leetcode.com/problems/shortest-path-in-a-grid-with-obstacles-elimination/description/",
  "https://leetcode.com/problems/number-of-ways-to-paint-n-3-grid/description/",
  "https://leetcode.com/problems/maximum-non-negative-product-in-a-matrix/description/",
  "https://leetcode.com/problems/create-maximum-number/description/",
  "https://leetcode.com/problems/combination-sum-iv/description/",
  "https://leetcode.com/problems/freedom-trail/description/",
  "https://leetcode.com/problems/out-of-boundary-paths/description/ 3d",
  "https://leetcode.com/problems/find-the-sum-of-the-power-of-all-subsequences/description/ 2d / 3d impo hard",
  "https://leetcode.com/problems/maximum-strength-of-k-disjoint-subarrays/description/ 3d hard impo",
  "https://leetcode.com/problems/knight-probability-in-chessboard/description/",
  "https://leetcode.com/problems/champagne-tower/description/",
  "https://leetcode.com/problems/largest-sum-of-averages/description/",
  "https://leetcode.com/problems/minimum-number-of-refueling-stops/description/",
  "https://leetcode.com/problems/number-of-music-playlists/description/",
  "https://leetcode.com/problems/video-stitching/description/",
  "https://leetcode.com/problems/longest-arithmetic-subsequence/description/",
  "https://leetcode.com/problems/minimum-falling-path-sum-ii/description/",
  "https://leetcode.com/problems/stone-game-ii/description/",
  "https://leetcode.com/problems/number-of-dice-rolls-with-target-sum/description/",
  "https://leetcode.com/problems/count-vowels-permutation/description/",
  "https://leetcode.com/problems/dice-roll-simulation/description/",
  "https://leetcode.com/problems/minimum-distance-to-type-a-word-using-two-fingers/description/",
  "https://leetcode.com/problems/minimum-difficulty-of-a-job-schedule/description/",
  "https://leetcode.com/problems/build-array-where-you-can-find-the-maximum-exactly-k-comparisons/description/",
  "https://leetcode.com/problems/number-of-ways-of-cutting-a-pizza/description/",
  "https://leetcode.com/problems/paint-house-iii/description/",
  "https://leetcode.com/problems/count-all-possible-routes/description/",
  "https://leetcode.com/problems/number-of-sets-of-k-non-overlapping-line-segments/description/",
  //graph/tree
  "https://leetcode.com/problems/find-the-maximum-sum-of-node-values/description/",
  "https://leetcode.com/problems/unique-binary-search-trees-ii/description/",
  "https://leetcode.com/problems/house-robber-iii/description/",
  "https://leetcode.com/problems/find-the-shortest-superstring/description/",
  "https://leetcode.com/problems/binary-tree-cameras/description/",
  "https://leetcode.com/problems/kth-ancestor-of-a-tree-node/description/",
  "https://leetcode.com/problems/maximum-product-of-splitted-binary-tree/description/",
  "https://leetcode.com/problems/longest-zigzag-path-in-a-binary-tree/description/",
  "https://leetcode.com/problems/linked-list-in-binary-tree/description/",
  "https://leetcode.com/problems/number-of-ways-to-reorder-array-to-get-same-bst/description/",
  //intervals/mcm
  "https://leetcode.com/problems/minimum-score-triangulation-of-polygon/?envType=list&envId=50vtr1g3",
  "https://leetcode.com/problems/parsing-a-boolean-expression/description/",
  "https://leetcode.com/problems/arithmetic-slices/description/",
  "https://leetcode.com/problems/predict-the-winner/description/",
  "https://leetcode.com/problems/strange-printer/description/",
  "https://leetcode.com/problems/stone-game/description/",
  "https://leetcode.com/problems/valid-permutations-for-di-sequence/description/",
  "https://leetcode.com/problems/last-stone-weight-ii/description/",
  "https://leetcode.com/problems/allocate-mailboxes/description/",
  "https://leetcode.com/problems/stone-game-vii/description/",
  "https://leetcode.com/problems/stone-game-v/description/",
  "https://leetcode.com/problems/guess-number-higher-or-lower-ii/description/",
  "https://leetcode.com/problems/remove-boxes/description/",
  "https://leetcode.com/problems/minimum-cost-to-merge-stones/description/",
  "https://leetcode.com/problems/minimum-cost-tree-from-leaf-values/description/",
  "https://leetcode.com/problems/palindrome-partitioning-iii/description/",
  "https://leetcode.com/problems/palindrome-partitioning-iv/description/",
  //math
  "https://leetcode.com/problems/ugly-number-ii/description/",
  "https://leetcode.com/problems/race-car/description/",
  "https://leetcode.com/problems/new-21-game/description/",
  "https://leetcode.com/problems/super-egg-drop/description/",
  "https://www.geeksforgeeks.org/problems/egg-dropping-puzzle-1587115620/1",
  "https://leetcode.com/problems/least-operators-to-express-number/description/",
  "https://leetcode.com/problems/largest-multiple-of-three/description/",
  "https://leetcode.com/problems/airplane-seat-assignment-probability/description/",
  "https://leetcode.com/problems/minimum-one-bit-operations-to-make-integers-zero/description/",
  "https://leetcode.com/problems/count-sorted-vowel-strings/description/",
  "https://leetcode.com/problems/stone-game/description/",
  //bits
  "https://leetcode.com/problems/can-i-win/description/",
  "https://leetcode.com/problems/stickers-to-spell-word/description/",
  "https://leetcode.com/problems/partition-to-k-equal-sum-subsets/description/",
  "https://leetcode.com/problems/shortest-path-visiting-all-nodes/description/",
  "https://leetcode.com/problems/smallest-sufficient-team/description/",
  "https://leetcode.com/problems/maximum-students-taking-exam/description/",
  "https://leetcode.com/problems/number-of-ways-to-wear-different-hats-to-each-other/description/",
  "https://leetcode.com/problems/minimum-cost-to-connect-two-groups-of-points/description/",
  "https://leetcode.com/problems/maximum-number-of-achievable-transfer-requests/description/",
  "https://leetcode.com/problems/distribute-repeating-integers/description/",
  "https://leetcode.com/problems/maximize-grid-happiness/description/",
  "https://leetcode.com/problems/find-minimum-time-to-finish-all-jobs/description/",
  //digit
  "https://leetcode.com/problems/non-negative-integers-without-consecutive-ones/description/",
  "https://leetcode.com/problems/numbers-at-most-n-given-digit-set/description/",
  "https://leetcode.com/problems/numbers-with-repeated-digits/description/",
  "https://leetcode.com/problems/maximum-height-by-stacking-cuboids/",
  "https://leetcode.com/problems/minimum-number-of-removals-to-make-mountain-array/",
  "https://leetcode.com/problems/longest-subsequence-repeated-k-times/description/",
  "https://leetcode.com/problems/jump-game/description/",
  "https://practice.geeksforgeeks.org/problems/ncr1019/1",
  "https://leetcode.com/problems/pascals-triangle/description/",
  "https://leetcode.com/problems/constrained-subsequence-sum/description/",
  "https://leetcode.com/problems/count-palindromic-subsequences/description/",
  "https://leetcode.com/discuss/general-discussion/1367659/count-derangements-permutation-such-that-no-element-appears-in-its-original-position",
  "https://leetcode.com/problems/scramble-string/description/",
  "https://leetcode.com/problems/distinct-subsequences-ii/description/",
  "https://leetcode.com/problems/delivering-boxes-from-storage-to-ports/description/",
];
const bits$math = [
  "https://www.geeksforgeeks.org/problems/least-prime-factor5216/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article",
  "https://www.geeksforgeeks.org/problems/prime-factorization-using-sieve/1",
  "https://www.geeksforgeeks.org/problems/largest-prime-factor2601/1?itm_source=geeksforgeeks&itm_medium=article&itm_campaign=bottom_sticky_on_article",
  
];

const topics = [
  arr,
  binSrch,
  twoPtr,
  strings,
  srch$sort,
  rec$bt,
  s$q,
  slidingWindow,
  ll,
  greedy,
  tree$bst,
  fenwickTree,
  heap$hash,
  tries,
  graphs,
  dp,
  st,
  bits$math,
];

const t = (topic) =>
  console.log(topic[Math.floor(Math.random() * topic.length)]);

const q = () =>
  console.log(
    topics[Math.floor(Math.random() * topics.length)][
      Math.floor(
        Math.random() * topics[Math.floor(Math.random() * topics.length)].length
      )
    ]
  );

t(graphs);
t(dp);
t(dp);
q();

let ans = 0;
for (let topic of topics) ans += topic.length;
console.log(ans + " more to go");
